// webResUrl
/* 存放网站资源所需要的路径
 * 部分图片具有尺寸大小
 * sm md lg xl
 * 尺寸统一为：[sm<=100px,md<=300px,lg<=500px,xl>=720px,xxl>=1080px]
 * 颜色默认为原来颜色或则白色，特殊颜色用red、black、blue、green等注明
 * 多个字符采用驼峰命名，否则会报错
 */
const webUrl={
	"faviconIco":"http://img.mabylove.cn/rootImg/icon/favicon.ico",
	"navLogo":{
		"smBlack":"http://img.mabylove.cn/rootImg/webpicture/logo100.png",
		"sm":"http://img.mabylove.cn/rootImg/webpicture/logo100f.png",
		"lgBlack":"http://img.mabylove.cn/rootImg/webpicture/logo500.png",
		"lg":"http://img.mabylove.cn/rootImg/webpicture/logo500f.png"
	},
	"logo":{
		"sm":"http://img.mabylove.cn/rootImg/logo/logoP100.png",
		"mdSm":"http://img.mabylove.cn/rootImg/logo/logoP200.png",
		"md":"http://img.mabylove.cn/rootImg/logo/logoP300.png",
		"sm":"http://img.mabylove.cn/rootImg/logo/logoP500.png"
	},
	"banner":{
		"xlBlack":"http://img.mabylove.cn/rootImg/banner/bannerBlack1-720.jpg",
		"xxlBlack":"http://img.mabylove.cn/rootImg/banner/bannerBlack1-1080.jpg",
		"xlBlue":"http://img.mabylove.cn/rootImg/banner/bannerBlue1-720.jpg",
		"xxlBlue":"http://img.mabylove.cn/rootImg/banner/bannerBlue1-1080.jpg",
		"xlRed":"http://img.mabylove.cn/rootImg/banner/bannerRed1-720.jpg",
		"xxlRed":"http://img.mabylove.cn/rootImg/banner/bannerRed1-1080.jpg",
		"xlWhite":"http://img.mabylove.cn/rootImg/banner/bannerLove1-720.jpg",
		"xxlWhite":"http://img.mabylove.cn/rootImg/banner/bannerLove1-1080.jpg"
	},
	"homeMethod":{
		"one":{
			"md":"http://img.mabylove.cn/rootImg/webpicture/pc1-300.png",
			"lg":"http://img.mabylove.cn/rootImg/webpicture/pc1-500.png"
		},
		"two":{
			"md":"http://img.mabylove.cn/rootImg/webpicture/moneymanage-300.png",
			"lg":"http://img.mabylove.cn/rootImg/webpicture/moneymanage-500.png"
		}
	},
	"homeIcon":{
		"one":{
			"sm":"http://img.mabylove.cn/rootImg/webpicture/application/growup100.png",
			"md":"http://img.mabylove.cn/rootImg/webpicture/application/growup300.png",
			"lg":"http://img.mabylove.cn/rootImg/webpicture/application/growup500.png"
		},
		"two":{
			"sm":"http://img.mabylove.cn/rootImg/webpicture/application/displayproduct100.png",
			"md":"http://img.mabylove.cn/rootImg/webpicture/application/displayproduct300.png",
			"lg":"http://img.mabylove.cn/rootImg/webpicture/application/displayproduct500.png"
		},
		"three":{
			"sm":"http://img.mabylove.cn/rootImg/webpicture/application/platform100.png",
			"md":"http://img.mabylove.cn/rootImg/webpicture/application/platform300.png",
			"lg":"http://img.mabylove.cn/rootImg/webpicture/application/platform500.png"
		},
		"four":{
			"sm":"http://img.mabylove.cn/rootImg/webpicture/application/ourself100.png",
			"md":"http://img.mabylove.cn/rootImg/webpicture/application/ourself300.png",
			"lg":"http://img.mabylove.cn/rootImg/webpicture/application/ourself500.png"
		},
		"five":{
			"sm":"http://img.mabylove.cn/rootImg/webpicture/application/technologyshare100.png",
			"md":"http://img.mabylove.cn/rootImg/webpicture/application/technologyshare300.png",
			"lg":"http://img.mabylove.cn/rootImg/webpicture/application/technologyshare500.png"
		},
		"six":{
			"sm":"http://img.mabylove.cn/rootImg/webpicture/application/diyweb100.png",
			"md":"http://img.mabylove.cn/rootImg/webpicture/application/diyweb300.png",
			"lg":"http://img.mabylove.cn/rootImg/webpicture/application/diyweb500.png"
		}
	},
	"taskPic":{
		"create":{
			"xl":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/create_task1000.png",
			"lg":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/create_task500.png",
			"md":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/create_task300.png",
			"sm":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/create_task200.png",
		},
		"manage":{
			"xl":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/task_manage1000.png",
			"lg":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/task_manage500.png",
			"md":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/task_manage300.png",
			"sm":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/task_manage200.png",
		},
		"execute":{
			"xl":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/execute_task1000.png",
			"lg":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/execute_task500.png",
			"md":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/execute_task300.png",
			"sm":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/execute_task200.png",
		},
		"echarts":{
			"xl":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/echarts_task1000.png",
			"lg":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/echarts_task500.png",
			"md":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/echarts_task300.png",
			"sm":"http://img.mabylove.cn/studyImg/taskPick/taskIcon/echarts_task200.png",
		}
	},
	"background":{
		"xxlCity":"http://img.mabylove.cn/rootImg/city-null-1200.png",
		"city":"http://img.mabylove.cn/rootImg/city-null.png"
	},
	"default":{
		"headPic":"http://img.mabylove.cn/defaultImg/headPic/001.png",
	}
}

export default webUrl;